[project]
name = "stiv_control"
version = "0.1.0"
description = "Package description here."
authors = [{name="Joshua Taggart", email="jftaggart02@gmail.com"}]
license = {text = "MIT"}
dependencies = [
]